### ISSUE TITLE
go to definition seems to only work for open files

### ISSUE THREAD

**Issue by adammenges** [atom/ide-typescript#101]
Go to definition (command click) only seems to work as expected if the file where it's defined it also open in a different tab in the same window. The status icon says 'idle' so I assume it's done indexing or whatever needs to happen there. What am I missing? Some setting somewhere?

Sometimes if the file isn't open it's jump to the function/class/react component import at the top of the file, not it's actual definition

vs if that file is open it'll just there

help that makes sense, lmk if you need more info

**Comment by damieng** [comment]
Should be fixed with the new ide-typescript 0.8.0 update.
