### ISSUE TITLE
TypeScript syntax in .js files are errors even with FlowType

### ISSUE THREAD

**Issue by vsanthanam** [atom/ide-typescript#104]
I've got several files in my project that at are checked with FlowType. (the // @flow is at the top of the .jsx file)

Flow files allow type declarations .js and .jsx files, but the IDE still tells me that they aren't allowed in .js and .jsx files and is asking me to switch to .ts and .tsx files. Is there a way to ignore these kinds of errors, or else make the idea smart enough to ignore these kinds of errors on .js and .jsx files that are designed for use with flow?

**Comment by vsanthanam** [comment]
![screen shot 2018-04-03 at 11 52 59 am](https://user-images.githubusercontent.com/3914230/38269523-a01848da-3735-11e8-853c-4d7f54fa84a8.png)

**Comment by damieng** [comment]
If you have a .flowconfig in your root the ide-typescript package can ignore all .js files and just do .ts files.

Unfortunately it is not possible for us to just ignore js files with `// @flow` in them - the protocol and the server just doesn't have that level of control of the process.

The other option would be to go into the settings for ide-typescript and set 'diagnosticsEnabled' so you can keep outline view etc. but entirely turn off the errors and warnings.
