### ISSUE TITLE
Issue with ".es6" file extension

### ISSUE THREAD

**Issue by peterramsing** [atom/ide-typescript#106]
## Versions:
* Atom: 1.25.1
* atom-ide-ui: 0.9.4
* ide-typescript: 0.7.6

## Issue:
For various reasons the codebase I'm working in uses `.es6` as the file extension for our javascript files. When editing these files none of the features of ide-typescript are available.

## Tried:
* Confirmed that the grammar was `source.js` 
* Edited the sourcecode for ide-typescript to include the extension `.es6` **did not fix issue**
* Renamed the file to have the `.js` file extension and the features of ide-typescript became available.

Let me know if I can provide any other information. I'm not sure if this is even in the hands of this plugin as it might be a part of the language server but it doesn't feel like it is as the grammar is correct and all my other plugings that interact to javascript files are working just fine.

Thanks so much! 😀

**Comment by damieng** [comment]
This is a limitation of the underlying Typescript server - they would need to support the file extension type as they are responsible for crawling the FS for all relevant information.  They are tracking this request at https://github.com/Microsoft/TypeScript/issues/15416

**Comment by peterramsing** [comment]
Cool. I figured it might be out of scope here. Thanks!
