### ISSUE TITLE
Missing Symbol Find Support

### ISSUE THREAD

**Issue by deathgaze** [atom/ide-typescript#108]
Cmd/Ctrl - R to find symbols doesn't work with this package. Perhaps we could pull in symbol find from atom-typescript?

**Comment by damieng** [comment]
cmd-R is the Atom Symbols Viewer package which is entirely based around ctags and has no knowledge of language servers.

You can either right-click and choose `Find References` - it should have a shortcut key assigned to it. You could always remap it to the Cmd-R if you don't use the symbols view package.
