### ISSUE TITLE
stage 0 from babel

### ISSUE THREAD

**Issue by patriciussanctus** [atom/ide-typescript#110]
Sorry if I made a mistake with place for repository's issue.
If I understand correctly, if i use only javascript, without ts, does not matter i must use this package?

I use babel stage-0 with [transform-function-bind](https://babeljs.io/docs/plugins/transform-function-bind/). And diagnostics shoots wrong//

<img width="585" alt="2018-05-11 14 44 01" src="https://user-images.githubusercontent.com/16253399/39922847-d06cb5fe-5529-11e8-9b15-05ce0b45f7a3.png">

**Comment by damieng** [comment]
TypeScript is a superset of JavaScript so also supports plain JavaScript however it does not support either Babel or any stage-x TC39 proposals.
