### ISSUE TITLE
Uncaught SyntaxError: Unexpected token  in JSON at position 227

### ISSUE THREAD

**Issue by vocariz** [atom/ide-typescript#111]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.7.6

### Stack Trace

Uncaught SyntaxError: Unexpected token 
 in JSON at position 227

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token 
 in JSON at position 227
    at JSON.parse (<anonymous>)
    at StreamMessageReader.onData (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:219:29)
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### Commands

```
  2x -9:25.2.0 core:backspace (input.hidden-input)
     -9:19 snippets:previous-tab-stop (input.hidden-input)
     -9:19 editor:outdent-selected-rows (input.hidden-input)
     -9:17.9.0 core:save (input.hidden-input)
     -8:46.4.0 core:backspace (input.hidden-input)
     -8:45.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-formatter-jsbeautify 1.1.2 
atom-ide-ui 0.11.2 
formatter 2.12.4 
ide-typescript 0.7.6 
language-babel 2.85.0 
navigate 0.1.20 
oceanic-next 1.0.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm what were you doing at the time of the error and if the error is reproducible?

**Comment by vocariz** [comment]
You're welcome!

I wish I could remember, it hasn't happen ever again. I just started Atom,
as every day, and the error showed up.


2018-05-14 22:40 GMT+02:00 Robert Sese <notifications@github.com>:

**Comment by rsese** [comment]
Thanks :+1:  Since it's not reproducible for you we'll go ahead and close for now.
