### ISSUE TITLE
+100% when opening an Ember project with `ide-typescript` installed

### ISSUE THREAD

**Issue by erkie** [atom/ide-typescript#113]
Using version `0.7.6`, running Atom `1.27.2 x64` with `atom-ide-ui` `0.12.0` and I just updated all packages to the latest version, but this has been going on for so long now and so many versions of both Atom and other packages.

Whenever I start Atom with an Ember.js project folder, the `Atom Helper` process kicks up to 100-130% constantly. When I close the Ember.js and force stop the `Atom Helper` process, it stops. If I disable the `ide-typescript` module, and force stop the `Atom Helper` process, it stops happening too.

I tried reproducing it with an empty Ember-repo but couldn't, so there must be something in my project triggering this. So any help to debug this would be much appreciated.

Node version:

```
$ node --version
v8.11.2
```

**Comment by lucacorti** [comment]
Maybe related to #95 ?

**Comment by erkie** [comment]
Yeah, I think so too. I had a `404mb` `/tmp` directory that I deleted and it doesn't happen now. Ember works hard to generate a lot of files and folders, so I guess it's related.

**Comment by lucacorti** [comment]
I think this is not solved though. I'm eventually encountering the same issue again after deleting `tmp`.

**Comment by erkie** [comment]
No, unfortunately the people at https://github.com/sourcegraph/javascript-typescript-langserver/issues/453 seem to not want to fix it really ☹️When you run into this, can you try running `tree` to see if you get any symlink cycles? I think the easiest way is to just run `tree` and cmd+f in your terminal for `../..` or grep but then you need to escape the `.`
