### ISSUE TITLE
experimentalDecorators throwing ts errors in ide-typescript but not by tsc

### ISSUE THREAD

**Issue by radfahrer** [atom/ide-typescript#115]
I'm working on a typescript project with a .tsconfig.json that specifies `"experimentalDecorators": true` so when running `tsc` manually no errors are thrown. 

However when I use ide-typescript and there are decorators in the file being edited, ide-typescrpt marks them all. This makes it difficult to spot the legit errors that tslint is catching.

**Comment by radfahrer** [comment]
I have restarted both atom and my computer. Still seeing the same behavior.

**Comment by damieng** [comment]
Should be fixed with the new ide-typescript 0.8.0 update.
