### ISSUE TITLE
Code formatting does not work.

### ISSUE THREAD

**Issue by prednaz** [atom/ide-typescript#116]
I do not get any error message using it and indeed package.json states that code formatting is provided. It is just that nothing happens. For example it does not fix the indentation of this example.
```
if (true) {
let v = 42;
}

```

**Comment by damieng** [comment]
Code formatting is not supported.

A full list of features is contained in the readme.

**Comment by UziTech** [comment]
@prednaz You can use [`eslint-format`](https://atom.io/packages/eslint-format) for code formatting with atom-ide-ui and eslint
