### ISSUE TITLE
Outline view only works for typescript and not js files.

### ISSUE THREAD

**Issue by LeftBankTwo** [atom/ide-typescript#119]
I tried getting outline view to work on .js files, however I get a "No outline available, This is likely an error with the language package.".
So I tried just changing the file extension to '.ts' and outline view worked, of course I also got myriad error messages. I checked the package settings and I do indeed have 'JavaScript support' ticked and true. Is there anything I'm missing?

I'm on Atom v. 1.28.2 and running Linux 4.14.56-1-lts x86_64 GNU/Linux.

**Comment by ejgutierrez74** [comment]
I think this issue could be closed, in atom 1.30 it shows the outline in .js files ( im now using atom 1.31 in Ubuntu 18.04.1)

![captura de pantalla de 2018-10-02 11-12-14](https://user-images.githubusercontent.com/11474846/46339816-0c31f600-c634-11e8-9970-b04b59683f91.png)

**Comment by rsese** [comment]
Thanks @ejgutierrez74 - @LeftBankTwo are you still having the same problem on the latest versions of Atom?
