### ISSUE TITLE
Define atom-languageclient as a package dependency instead of node dependecy

### ISSUE THREAD

**Issue by Goodwine** [atom/ide-typescript#12]
This should allow changing atom-languageclient options rather than depending on the default options.

**Comment by damieng** [comment]
I don't understand what you are suggesting here or the problem it solves. Can you elaborate?

**Comment by Goodwine** [comment]
When I look for "atom-languageclient", I get [OmniSharp/atom-languageclient](https://github.com/OmniSharp/atom-languageclient), this package has several options which I can't change because atom-languageclient was installed as a node module instead of being used as package dependency.

**Comment by damieng** [comment]
OmniSharp/atom-languageclient is in no way related to this project.

What you need is the npm module atom-languageclient. 

The OmniSharp people have offered to rename or remove their package. I'll speak to them and figure out how to remove that confusion.

**Comment by Goodwine** [comment]
Oh... things make sense now. Thanks!
