### ISSUE TITLE
Get Diagnostics on Save only

### ISSUE THREAD

**Issue by ghivert** [atom/ide-typescript#123]
Hi!

When typing some lines into the editor, the plugin launches diagnostics as soon as it is possible. We end up in situations like typing `cons var =` and the compiler already print errors.

It would be much better to have the compiler running after saving a file, because errors showing up just because I'm not typing quick enough or because I'm thinking is disturbing.

Could there be an option for this?

**Comment by damieng** [comment]
Unfortunately because of the way the language server protocol works information is sent directly to the typescript compiler as it is worked on rather than on save so this is not possible without changes to the specification and language server itself.
