### ISSUE TITLE
Does ide-typescript work in new Atom?

### ISSUE THREAD

**Issue by xtuer** [atom/ide-typescript#125]
Does ide-typescript work in new Atom such as the latest version 1.30.0?
Tried in Mac and Windows both doesn't work!

A few things to know before you create an issue:

## Environments
Atom: 1.30.0
Mac: macOS High Sierra, Version: 10.13.6

## Problems
* The console only prompts the error: **Failed to load resource: net::ERR_NAME_NOT_RESOLVED: ide-typescript.svg** (Its url is https://david-dm.org/atom/ide-typescript.svg)
* There is a node helper uses CPU more than 120%.
* The Outline pane only shows loading status.

## Location
Used in China (Maybe blocked by the firewall?).

**Comment by rsese** [comment]
Can you be more specific?  When you say "doesn't work" do you mean no IDE functionality works at all?  Can you share a minimal test file that doesn't work for you?  Lastly, do you see any errors in [devtools console](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools)?

Also what operating system are you running?  I just tried Atom 1.30.0 on macOS 10.12.6 with a simple test JavaScript file and things worked ok (e.g. hyperclick and outline view worked) :

```javascript
let f = function(x, y) {
  return x + y;
};

console.log(f(1,2));
```

**Comment by xtuer** [comment]
@rsese Thank you for your reply, I appended more information in the question, hope it is useful.

**Comment by mattlyons0** [comment]
I'm also on OSX 10.13.6 Atom 1.30.0. I can't get it to do anything, things just spin.

Holding Command and hovering code sections shows the spinning cursor, hyperclick doens't work because of this, opening the outline shows a spinner forever. This all occurs in my codebase as well as the file included above.

Nothing is printed to console log, I have debugging enabled on the package.

**Comment by mattlyons0** [comment]
As it turns out I am able to get the plugin working in some repositories but not others, will move to a different issue.

**Comment by damieng** [comment]
It can sometimes take some time to index and scan your code depending on the size of the code base and the number of node_modules etc.

**Comment by mattlyons0** [comment]
Just as a follow-up, my problem was with symlink cycles (Lerna), something that is refused to be supported upstream (https://github.com/sourcegraph/javascript-typescript-langserver/issues/453)

**Comment by damieng** [comment]
Ah, good to know.  We are looking at switching to a different language server wrapper around the typescript compiler that hopefully will handle this better.
