### ISSUE TITLE
Unable to find files outside of my atom project.

### ISSUE THREAD

**Issue by Goodwine** [atom/ide-typescript#13]
(Not sure if this issue belongs here or if I should send it on a different package)

This plugin works way faster than `atom-typescript` o_o, However I have a small problem

Say that I have a file that imports anything from a library like Angular2Material, for example:

```typescript
import {MdDialogRef} from '@angular/material';
```

The ide plugin tells me that `ts: Cannot find module '@angular/material'`.
Is there a way to fix this?

My tsconfig.json which is located at the root of my atom project looks roughly like this (and is generated by a bazel plugin):

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "rootDirs": [
      "./",
      "../../../app/"
    ],
    "baseUrl": ".",
    "paths": {
      "app/*": [
        "./*",
        "../../../app/*"
      ],
      "@angular2-material/dialog": [
        "../../../angular2_material/src/lib/dialog"
      ],
      "@angular2-material/dialog/*": [
        "../../../angular2_material/src/lib/dialog/*"
      ],
      "@angular-material": [
        "../../../angular2_material/src/lib"
      ],
      "@angular-materia/*l": [
        "../../../angular2_material/src/lib/*"
      ]
    },
    "noEmitOnError": false,
    "declaration": false,
    "stripInternal": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "plugins": [
      {
        "name": "ide_performance"
      }
    ],
    "noEmit": true
  },
  "files": [
    "../../../angular2_material/src/lib/dialog/dialog-ref.d.ts",
    "../../../angular2_material/src/lib/dialog/dialog-ref.ngfactory.d.ts",
    "../../../angular2_material/src/lib/dialog/dialog-ref.ngsummary.d.ts",
    "./whatever.ts",
    "../../../app/whatever.ts"
  ],
  "compileOnSave": false
}
```

**Comment by damieng** [comment]
How that happens is really going to be down to the Typescript language server itself which we just wrap up for Atom (although SourceGraph wrap it in the middle).

Do you know if it works in VSCode?

**Comment by Goodwine** [comment]
On VSCode, you can add this to settings `"typescript.tsdk": "./node_modules/typescript/lib",` and I can make vscode point to my own version of the typescript node module.
But I'm not sure if sourcegraph/javascript-typescript-langserver uses it.

**Comment by Goodwine** [comment]
Interesting, I had no idea how to attach a debugger to the server (and I still don't), but I found out that I could enable the logger by setting `atom.config.set('core.debugLSP', true)`
For some reason it seems like project-manager in the javascript-typescript-langserver is unable to load the content of the given files. for example... it's able to list the files from my project but then it has a process where it uses `InMemoryFileSystem` to load all files and filter out those that don't match `[tj]sconfig.json`, contain `/node_modules/`, or are empty, and for some reason the contents are `undefined`, soo... I don't know what's up :slightly_frowning_face:

**Comment by Goodwine** [comment]
nvm, I'll keep trying to debug this, it seems I did actually load the tsconfig.json file

**Comment by Goodwine** [comment]
While I haven't discovered the root cause, it seems like if I have:

```typescript
// ~/a/b/myFile.ts
import {X} from '@x'

// ~/a/index.ts
export class X{}
```
```js
// ~/a/b/tsconfig.json
{
  //...
  baseUrl: '.',
  paths: { "@x": [../] }
}
```

If I don't have `../` in my atom project folders, then the server is not able to load the module. However it works fine if I include it.
i.e. `atom ~/a/b/` would replicate the issue, but `atom ~/a` would not.

Do you know where should I go to investigate further? As you mentioned, I don't think this is a bug in this plugin itself, but one in some dependency.

**Comment by damieng** [comment]
The processing of these paths actually happens in the Microsoft TypeScript server we rely on to perform the TypeScript AND JavaScript language analysis.  It would need to be supported there.
