### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by wolfy1339** [atom/ide-typescript#130]
This plugin is using the CPU a lot at random times, even when the editor is open, but inactive.
The only way i've found is to kill it via Task Manager until it goes over the restart limit, so it doesn't restart by itself.

**Comment by erkie** [comment]
Does it happen when you have certain projects open? There are some issues with the typescript language server and folders with recursive symlinks.

**Comment by wolfy1339** [comment]
It happens on JavaScript files. It'll try to generate the outline and jut continues and continues on, until it times out after a long time. But if i open the same file in a typescript project, it works just fine

**Comment by damieng** [comment]
Can you try this with new ide-typescript 0.8.0 update?

**Comment by wolfy1339** [comment]
I can confirm that this is no longer a problem

________________________________
