### ISSUE TITLE
It doeent work in Atom 1.30

### ISSUE THREAD

**Issue by ejgutierrez74** [atom/ide-typescript#131]
Atom: 1.30.0
Plugin: latest version
SO: Ubuntu 18.04.1 64 bits

I have installed ide-typescript along atom-ide-ui and ide-html and ide-css.... and it seems it doesnt work... not error or warning messages not inline html file or in .js file...

Dont know if i have to set some config....

![captura de pantalla de 2018-09-24 14-23-21](https://user-images.githubusercontent.com/11474846/45952042-03bf3700-c006-11e8-9cae-400be62ed381.png)
![captura de pantalla de 2018-09-24 14-23-18](https://user-images.githubusercontent.com/11474846/45952046-06219100-c006-11e8-807b-2cbc23520c81.png)

It seems it works at least in .js files not in html if i enable the linter-jshint, but it shouldnt be necessary.... ide_typescript must show errors and warnings using atom-ide-diagnostic....

I also have the atom-ide-diagnostic as you can watch in the images...

Im looking for javascript, html and css plugins to show me errors and warnings....just in case you know or use some.

Thanks

**Comment by damieng** [comment]
The typescript compiler does not support typescript inside HTML files and so we are also unable to process typescript contained in these files.  

This is also a limitation of the language server protocol which I hope will one day be addressed there but it is not possible for Atom to do this without that support.

**Comment by ejgutierrez74** [comment]
Sorry, but just one question why is linter-jshint and linter-jscs working ? Are they using different language server ? Thanks

**Comment by damieng** [comment]
They are hinting packages that do some analysis that can work on .html files. The typescript compiler used behind the scenes here only does .ts and .js files.

**Comment by sagarguhe** [comment]
this plugin stopped indexing, linting and Hyperclick not working anymore, I am working `.tsx` file. previously it was working fine. 
Atom: 1.31.2
ide-typescript: 0.7.9
