### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ejgutierrez74** [atom/ide-typescript#132]
It would be nice as you can enable/diable javascript, you could enable/disble typescript ( to use this ide with javascript as is till now the only one ide for javascript).

The second option would be to choose between standard and google javascript.
Also would be nice to warn about semicolons at the end of the line like linter-jshint.

Thanks

**Comment by damieng** [comment]
We are limited by the features available in the TypeScript compiler we use for JavaScript support so could not choose between different standards other than the ESxxxx ones that tsc currently supports.
