### ISSUE TITLE
Outline not working with ".js" files

### ISSUE THREAD

**Issue by DenysMb** [atom/ide-typescript#140]
Hi, the outline is not working for me with ".js" files in Atom Beta (1.33.0-beta1) nor in Atom Stable.
I have a project with React and the outline view is empty when editing one of the ".js" files of the project (FIRST IMAGE) and when I created a ".js" file in my desktop and made a simple function the outline says "No outline avaible" (SECOND IMAGE).
The Typescript is instaled (THIRD IMAGE).
But my Atom is installed without ADMIN privileges and even the ".ts" files do the mesage "No outline avaible" (FOURTH IMAGE)

![image](https://user-images.githubusercontent.com/33737137/48263349-ea831600-e40c-11e8-857d-41a8e0b90e03.png)

![image](https://user-images.githubusercontent.com/33737137/48263320-d2ab9200-e40c-11e8-9cce-0bac111cbce3.png)

![image](https://user-images.githubusercontent.com/33737137/48263595-bfe58d00-e40d-11e8-806e-bd544310732a.png)

![image](https://user-images.githubusercontent.com/33737137/48263731-4601d380-e40e-11e8-9a24-c9bd3e980be2.png)

**Comment by wolfy1339** [comment]
I have the same issue, and it's happening for TS files as well.
JSON files are okay

**Comment by Sendao** [comment]
Same issue... typescript ide support does not work.

**Comment by Ivo04** [comment]
Yes, I have the same problem on my Laptop, but not on my PC. But I think that I have an older version on my PC. I can look again and tell you the versions. (If I find the version numbers ;)

**Comment by Ivo04** [comment]
Yes, I have the same problem on my Laptop, but not on my PC. But I think that I have an older version on my PC. I can look again and tell you the versions. (If I find the version numbers ;)

**Comment by Ivo04** [comment]
Yes, I have the same problem on my Laptop, but not on my PC. But I think that I have an older version on my PC. I can look again and tell you the versions. (If I find the version numbers ;)

**Comment by Ivo04** [comment]
Yes, I have the same problem on my Laptop, but not on my PC. But I think that I have an older version on my PC. I can look again and tell you the versions. (If I find the version numbers ;)

**Comment by Ivo04** [comment]
Yes, I have the same problem on my Laptop, but not on my PC. But I think that I have an older version on my PC. I can look again and tell you the versions. (If I find the version numbers ;)

**Comment by Ivo04** [comment]
Yes, I have the same problem on my Laptop, but not on my PC. But I think that I have an older version on my PC. I can look again and tell you the versions. (If I find the version numbers ;)

**Comment by Aerijo** [comment]
@Ivo04 Something up with you're submit button?

**Comment by Ivo04** [comment]
Sorry for my posts, I pressed the comment button and nothing happend, so I pressed again and again and again.....
Sorry

**Comment by Ivo04** [comment]
I found the version numbers and both are the same versions but only on my PC the outline works.
The OS is the same too. (Linux Mint 19 Tara Cinnamon 64 bit)

**Comment by Sendao** [comment]
I have hacked together an outline for another part of Atom if anybody wants to get back to coding it's in my profile. I don't want to link it directly because I'm not sure what the rules or etiquette are in this situation. It works, that's what matters.

**Comment by damieng** [comment]
Can you try this with new language server - try ide-typescript 0.8.0

**Comment by wolfy1339** [comment]
I can confirm that it is indeed fixed

________________________________
