### ISSUE TITLE
v0.8.0 does not parse JSX in .tsx files

### ISSUE THREAD

**Issue by aergonaut** [atom/ide-typescript#145]
Upgrading to v0.8.0 of the package seems to break JSX in .tsx files.

With v0.8.0, all of the JSX tags in my .tsx files are highlighted as errors, with error messages like "Cannot find name span", etc. Additionally, the `import React from "react"` import at the top of my files is highlighted as unused.

With v0.7.9, there are no errors in my files.

As an example, you can check this file from one of my public projects: https://github.com/aergonaut/jiken/blob/master/app/javascript/incidents/Incident.tsx

**Comment by aergonaut** [comment]
Thanks for the workaround @mcous. Turning off tree-sitter also fixes the problem for me.

**Comment by dfrankland** [comment]
I still needed to use `tree-sitter` for other languages like Rust, so I instead removed the `tree-sitter` grammars from the `language-typescript` package and then everything worked out fine with the "Core > Use Tree Sitter Parsers" still enabled.

1.  Install `language-typescript` with `apm` even though it is bundled with Atom:

    ```bash
    apm install language-typescript
    ```

2.  Then delete the `tree-sitter` grammars from the `language-typescript` package:

    ```bash
    rm ~/.atom/packages/language-typescript/grammars/tree-sitter*.cson
    ```

**Comment by adammenges** [comment]
Thanks, turning off tree-sitter worked for me too. Hopefully I'll be able to re-enable it again soon.
