### ISSUE TITLE
Grammar scopes with JSX/TSX

### ISSUE THREAD

**Issue by deankevorkian** [atom/ide-typescript#15]
since [`getGrammarScopes`](https://github.com/atom/ide-typescript/blob/master/lib/main.js) applies on `source.ts', 'source.js', 'source.js.jsx'` in case javascript support is enabled, shouldn't the package be active '.tsx' files as well?
Also, any particular reason why jsx files are identified by the `source.js.jsx` template and not `source.jsx`?
(Sorry if this was brought up before, didn't see any PR/issue related to this)

**Comment by damieng** [comment]
The scopes are really what the language grammar supports decide to name the type of files.

The JSX support has been tested with https://github.com/gandm/language-babel which does not support typescript (and therefore not TSX).

Our own typescript package - language-typescript - also does not yet support TSX.

If there is a good tsx language grammar for Atom please let me know and I'll make sure the grammar scope is correctly added.

**Comment by deankevorkian** [comment]
[Why not use the atom-typescript tsx grammar?](https://github.com/TypeStrong/atom-typescript/blob/master/grammars/tsx.cson)

**Comment by damieng** [comment]
Are you asking if we can put "source.tsx" in our grammar list (yes) or whether we can adopt/ship/support atom-typescript's grammars? (that's a bunch off logistical effort - I did originally reach out to them on gitter before creating language-typescript but got no response)

**Comment by deankevorkian** [comment]
atom-typescript have a grammar.ts script that generates a cson grammar file of the latest version of Microsoft TypeScript Textmate grammar, which you used for the language-typescript package.
I tried to fork the language-typescript package and make a language-typescript-react package, using updated grammars for tsx, [here](https://atom.io/packages/language-typescript-react).
Does this help?

**Comment by damieng** [comment]
It actually appears I did include the source.tsx conversion in language-typescript so it was just a case of adding the scopes here.

**Comment by deankevorkian** [comment]
Yeah, when I forked language-typescript I saw there already was a tsx.json file. I assumed it wasn't updated or non-functional.. I'll remove my package, thanks for the reply 👍

**Comment by damieng** [comment]
Sorry for the confusion, I should have checked 😊
