### ISSUE TITLE
activationHooks prevent ide-typescript from activating when using language-babel package

### ISSUE THREAD

**Issue by Sergeeeek** [atom/ide-typescript#151]
I'm using `language-babel` for my syntax highlighting and `ide-typescript` stopped working with it since 0.9.0.

I managed to fix that problem by manually removing `activationHooks` which are hardcoded to use `language-javascript`. They were added in #103

**Comment by Aerijo** [comment]
@Sergeeeek Ahh, sorry about that. I'll make them package-agnostic.

**Comment by Sergeeeek** [comment]
@Aerijo Didn't expect you to fix it so fast :smiley:  Awesome, thanks!
