### ISSUE TITLE
Upgrade typescript version to support new language features

### ISSUE THREAD

**Issue by mneumark** [atom/ide-typescript#158]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
I tried to use a typescript feature that resulted in an error. Upon further research I realized its because this package uses typescript 3.1.6 and the feature I want got added in typescript 3.4.

Can we upgrade the version of typescript this package uses?

### Steps to Reproduce

1. create a file with a typescript const. Something like
```ts
const foo = { bar: 'baz', hello: 'world' } as const 
```
2. Notice an error pops up saying `Cannot find name "const"`

**Expected behavior:**
No error should occur. This is now a standard feature of typescript.

**Actual behavior:**
An error is occuring on perfectly valid typescript

**Reproduces how often:**
100% of the time

### Versions
Atom 1.39.1 on macOS
ide-typescript 0.9.1

**Comment by mattlyons0** [comment]
As a temporary workaround you can install a newer version of the typescript language server globally (`npm install -g typescript`) and go into the extension settings for `ide-typescript` and change the language server path to where `tsserver` was installed. You can find where it is installed by typing in a terminal window `which tsserver` (which was `/usr/bin/tsserver` for me on Linux).

**Comment by AlexGustafsson** [comment]
Do you happen to know if this adds support for `BigInt` syntax such as `345689754387345678n`?

**Comment by mattlyons0** [comment]
It looks like [Typescript 3.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html) added support for BigInt, upgrading the `tsserver` binary used to `3.2` or newer should add support for it.
