### ISSUE TITLE
Find an alternate data tip mechanism

### ISSUE THREAD

**Issue by brettz9** [atom/ide-typescript#159]
## Summary

Find some alternate data tip mechanism besides `atom-ide-ui`.

## Motivation

The repo for `atom-ide-ui`, the package on which you apparently rely for datatips, has been archived. When I enable this package, I keep getting error messages as described at https://github.com/facebookarchive/atom-ide-ui/issues/306 so long as I also have the `linter` package enabled--a modern package which is used by many linters.

(I don't think you could just switch to `linter`, as its line item tooltips are apparently for the whole line.)

## Describe alternatives you've considered

1. Deal with the error message on every start-up. This is annoying.
2. Avoid using the tooltips feature. This feature is too useful to avoid using.

Thanks!

**Comment by Aerijo** [comment]
This package does not rely on `atom-ide-ui`. Package interaction in Atom is done with services, which are basically descriptions of what kind of information the package provides and consumes. This package allows it's dependencies provide the `definitions` service, and any package can consume it; there is nothing here that requires `atom-ide-ui`.

Granted, `atom-ide-ui` can handle a lot of the services in a nice and uniform way. It is also probably the origin of a lot of IDE related service APIs.

Closing as not something to be done; you would have to look for a package that handles the `datatips` service, or tweak the source of your local `atom-ide-ui` in some way. Normally I'd not advise that, but it's not like there will be any updates to stay on top of.
