### ISSUE TITLE
Document formatting

### ISSUE THREAD

**Issue by jbjonesjr** [atom/ide-typescript#16]
One of the things that I had used before the ide package was an eslint package that would fix many basic problems on file save (whitespace, some other things, can't remember now what else). This was incompatible with the ide-typescript package (was it `eslint`?), but i'd be curious if similar functionality was coming to the core ide-typescript package, or there are other packages that make good compliments to this package.

I'll hang up and listen ;)

**Comment by damieng** [comment]
Right now we're limited to what the Microsoft TypeScript server offers and it doesn't yet do this kind of formatting.

If they don't add that then one option would be indeed to consider using a separate tool alongside the server just to handle that piece of functionality.

**Comment by felixfbecker** [comment]
Developer on the TS langserver here. There is a WIP PR for supporting TS plugins like TSLint: https://github.com/sourcegraph/javascript-typescript-langserver/pull/327

Basic formatting would only require an implementation of the [`document/formatting`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_formatting) request to call the underlying TS language service.

**Comment by damieng** [comment]
I just checked in code to the package.json so we'll at least activate automatically once the language server reports the capability back as part of the initialization response.

**Comment by jbjonesjr** [comment]
Hey @damieng @felixfbecker . It looks like that sourcegraph PR is merged now, so plugins can be supported. Is the next step for someone to implement the `TSLint` plugin?

**Comment by felixfbecker** [comment]
Nope, that's already done: https://github.com/angelozerr/tslint-language-service

**Comment by jbjonesjr** [comment]
So.... atom is still reporting that code formatting is not enabled . `Failed to format code: No code formatting providers found!` Does this mean that @damieng configuration didn't actually pre-enable it?

**Comment by felixfbecker** [comment]
Document formatting !== TSLint. The [`textDocument/formatting` request](https://github.com/sourcegraph/language-server-protocol/blob/master/protocol.md#document-formatting-request) is not implemented in the language server.

**Comment by jbjonesjr** [comment]
@felixfbecker ah, i misunderstood your comment to be that the implementation was on the atom end (and what `damieng` was implementing). ok, back to waiting ;)

**Comment by damieng** [comment]
I'm not working on any document formatting - that will only activate if the language server supports it. We're not doing any language-server like implementations directly in Atom itself.

**Comment by felixfbecker** [comment]
@jbjonesjr why not do a PR? ;)

**Comment by mattijsf** [comment]
@jbjonesjr I was wondering, have you found another package that formats the document acceptably for the time being? Currently there is just no formatting available which is quite painful to be honest. I tried js-beautify but it doesn't seem to work with ide-typescript.

**Comment by jbjonesjr** [comment]
@felixfbecker 2 things:
- regardless of me opening a PR or not, i was hoping that my questions and discussion would at least better define what still needs to be done. I at least misunderstood some of the original comments, so maybe others did too.
- unfortunately, language server and document formatting is well out of my lane of expertise. That said, i'd be happy to install any PR-based package to test.

@mattijsf so after this conversation last week, I started searching for a formatter package again that `just works`. I settled on (and have been pretty happy with) [**Atom Beautify**](https://github.com/Glavin001/atom-beautify), which has worked really well for formatting without installing a bunch of other npm packages or dependencies. I operate across a few systems and environments, so I try to minimize the "install this package, then separately manage all this OS dependencies", and this did it for JS at least. Let me know if you find something better!

**Comment by mattijsf** [comment]
@jbjonesjr I tried Atom Beautify before. Initially I thought it didn't work because the built-in Format Code feature did not respond. Now I realised I had to call the package's specific beatify command. Changing the default Beautifier to _ESLint Fixer_ together with _Beatify on Save_ works pretty well for me.

Thanks!

**Comment by damieng** [comment]
Yes, they won't hook in to the atom-ide "format code" function without additional work but they should still be able to add their own command.  Glad you found one that works for you!
