### ISSUE TITLE
Linting Types is Overstepping

### ISSUE THREAD

**Issue by wldcordeiro** [atom/ide-typescript#19]
I'm using this server to get just the JavaScript features and have the flow server installed as well. I'm getting errors about defining flow types in my JS files. There should be some better detection of typescript before it applies the linting rule.

**Comment by damieng** [comment]
Can you provide a screen-shot?

**Comment by wldcordeiro** [comment]
![screen shot 2017-09-12 at 4 22 16 pm 2](https://user-images.githubusercontent.com/580982/30351013-91d81e02-97d6-11e7-9b11-ed7f9f890e89.png)
![screen shot 2017-09-12 at 4 22 37 pm](https://user-images.githubusercontent.com/580982/30351025-9fca69c0-97d6-11e7-8072-160428bff884.png)

**Comment by damieng** [comment]
I see.

The underlying TypeScript language server isn't capable of ignoring Flow annotations unfortunately.  It can treat files as plain JS or as TypeScript but not Flow.

You are best off using ide-flow if you are editing flow code. If you also want ide-typescript installed for typescript files you can turn off JS entirely for it from the Atom Settings page under ide-typescript.

**Comment by wldcordeiro** [comment]
But in a project that isn't using Typescript it shouldn't complain about type annotations in JS files.

**Comment by damieng** [comment]
The problem is a javascript file with flow type annotations isn't plain javascript.

**Comment by damieng** [comment]
I should clarify - if this was easy to achieve we would still do it. Unfortunately it's a limitation of the underlying language server that does all the hard work (Microsoft's TypeScript server)

**Comment by wldcordeiro** [comment]
There's no way to enable the JS portions of the server without the TypeScript portions? You have the checkbox in the settings for JS.

**Comment by damieng** [comment]
No.

**Comment by Arcanemagus** [comment]
@wldcordeiro The reason that can't be done is there are no "JS portions of the server". The LSP treats all code as TypeScript, it just happens to somewhat work for JS as TypeScript is for the most part a superset of JS. Where it fails is when you start using parts of JS (or non-JS like Flow) that TypeScript doesn't support.

**Comment by skylize** [comment]
> I should clarify - if this was easy to achieve we would still do it.

Flow files _should_ be annotated with `// @flow` or `/* @flow */` at the top of the file. This makes them _incredibly_ simple to identify. If typescript server finds a flow annotation at the top of the file, just don't process it any further or silence any results. What is hard about that?

**Comment by damieng** [comment]
@skylize The 'hard' part about that is we don't own the typescript server - Microsoft does.  They'll need to support it.

**Comment by skylize** [comment]
Ah, I see. And looking at your code I don't see anywhere the text content passes through for you to check it.

Worth recording here that this has been raised already upstream.
https://github.com/sourcegraph/javascript-typescript-langserver/issues/352
