### ISSUE TITLE
Now that nuclide-ide-ui is removed what is the corresponding package to install?

### ISSUE THREAD

**Issue by rwatts3** [atom/ide-typescript#2]
I see recent updates to change to atom ui packages, 
How do I install said packages to get the popups back. now that I've removed nuclide-atom-ui

**Comment by damieng** [comment]
You can continue to use nuclide - it supports these new service names - or you can use the specially-prepared atom-ide-ui package which is just the subset of nuclide we need.

**Comment by damieng** [comment]
The docs should be updated soon so all this will be clearer.
