### ISSUE TITLE
Typescript compilation

### ISSUE THREAD

**Issue by tomitrescak** [atom/ide-typescript#22]
Hi, is there any doc explaining how the compilation works? In my project "tsc" return no error. ide-typescript finds hundreds of errors. It looks like it is using some outdated Typescript version. Can this be somehow configured?

I even got error on "import * as React from 'react';" - `File '/Users/tomi/Github/packages/webpack2-typescript-2/node_modules/@types/react/index.d.ts' is not a module.`

But overall the first look is impressive!

**Comment by cupsadarius** [comment]
I'm getting this one too, typescript@2.4.2 works ok from cli but your integrated version throws some errors when importing modules

Ex: `import * as mysql from 'mysql';` i get
```
File '.../node_modules/@types/mysql/index.d.ts' is not a module.
```

**Comment by damieng** [comment]
Yes, we depend on javascript-typescript-langserver as the typescript server itself does not talk Microsoft's own language server protocol (despite me asking both the TS team and Anders :(  )

**Comment by lierdakil** [comment]
For anyone interested, here's a relevant TS issue https://github.com/Microsoft/TypeScript/issues/11274. When/if TypeScript implements LSP natively, this will be very straightforward to fix. Until then, probably not.

**Comment by cupsadarius** [comment]
@damieng @lierdakil thanks for the input, we'll have to wait and see.

**Comment by tomitrescak** [comment]
Yeah, thanks for the info! Will wait and see how this evolves.

**Comment by bronson** [comment]
Ah, that explains why `export default interface foo { }` shows tons of syntax errors in Atom, but `tsc` compiles it just fine.

2.3.4, oof: https://github.com/sourcegraph/javascript-typescript-langserver/blob/6087974050c313488b2497c1c7aee10a3d8b3a15/package.json#L53

It might help to change this issue's title to something like "ide-typescript uses an older version of typescript".

Wishing luck and smooth coding to the MS team.

**Comment by damieng** [comment]
The latest ide-typescript package now uses TypeScript 2.7.2 (the latest stable) so these specific errors should now be gone.

**Comment by ttsirkia** [comment]
I can still see the problem. For example, by using this repo: https://github.com/infernojs/inferno-typescript-example 

Compiling with `tsc` works fine.

**Comment by b-fuze** [comment]
I have the same issues with a JS file checked by TS
![image](https://user-images.githubusercontent.com/10504957/40623696-28d49460-6276-11e8-8f40-120b2cbe02d4.png)

**Comment by pyxarez** [comment]
@damieng , i just installed the package *ide-typescript* and see the same error as in the topic, can you please help?
Example:
- module
![image](https://user-images.githubusercontent.com/23152279/43523777-235f2eb0-95a6-11e8-8471-78ab64d0461d.png)
- error
![image](https://user-images.githubusercontent.com/23152279/43523786-2b685b18-95a6-11e8-836b-7c0c41ecbcbe.png)
- import
![image](https://user-images.githubusercontent.com/23152279/43523796-330fc6f8-95a6-11e8-937e-c821ad28348d.png)

**Comment by damieng** [comment]
A lot of these errors are being caused in a lower layer of ide-typescript known as the SourceGraph language server wrapper for TypeScript.

I'm working on switching ide-typescript away from that to a more reliable language server known as Theia which should solve this problem and many others.  It will be in the next release hopefully out in the next few days if we can sort out the remaining issues.
