### ISSUE TITLE
please support the webpack alias when finding reference

### ISSUE THREAD

**Issue by TinkGu** [atom/ide-typescript#27]
First, thanks for all your works! These ide-* packages are awesome!

We use the feature so-called "path alias" supported by webpack.

```javascript
// we use `@` instead `../../src`
import something from '@/a/b/c';
```

I found this syntax can not click to find reference.

Is there any way to solve it ?

**Comment by damieng** [comment]
This is entirely handled by the language servers so the TypeScript server would need to support this syntax.

**Comment by george-dotdev** [comment]
@damieng Should this work if the alias is specified in the tsconfig.json?

I don't get an error in the terminal but do in atom.

I have this in my tsconfig.
```
  "baseUrl": "src/scripts",
  "paths": {
    "types": ["components/types.d.ts"],
    "utils": ["modules/utils.ts"]
  }
```
Additionally I have this in my webpack config.
```
alias: {
  types: path.resolve('./src/scripts/components/types.d.ts'),
  utils: path.resolve('./src/scripts/modules/utils.ts'),
},
```

In atom I get the following error message
![image](https://user-images.githubusercontent.com/41870207/74497558-22dba300-4f32-11ea-92af-81ddb76f3f3d.png)
****

**Comment by damieng** [comment]
Sorry, I really don't know. It's been two years since I left GitHub and I haven't touched webpack since :(  (and Atom for over a year)
