### ISSUE TITLE
Disabling provider doesn't remove reported diagnostics

### ISSUE THREAD

**Issue by Arcanemagus** [atom/ide-typescript#29]
If a file has diagnostics reported for it from this provider, and this provider is then disabled the diagnostics are not removed. If the provider is then re-enabled a _new_ set of diagnostics is reported, doubling the first set.

![2017-09-13_14-28-28](https://user-images.githubusercontent.com/427137/30401646-dde28940-988f-11e7-85af-d568856bfcde.gif)

Atom: 1.21.0-beta0
`atom-ide-ui`: 0.3.1

**Comment by damieng** [comment]
Actually a bug in atom-languageclient, fixing there.
