### ISSUE TITLE
Package shows up in Atom but not clear if running

### ISSUE THREAD

**Issue by rcjsuen** [atom/ide-typescript#3]
Hi, I'm on Windows 10 and running Atom 1.18.0 x64.

I cloned the repository into `~/.atom/dev/packages` and ran `npm install` inside. I then started atom with `atom.exe -d`. The package shows up in the UI but it's not at all clear to me that it's running. I tried hovering over functions like `substring` or `console.log` in both JavaScript and TypeScript files. I tried hitting Ctrl+Space but nothing seems to happen although maybe that's related to #1.

How can I verify that the package has installed properly and is running?

**Comment by damieng** [comment]
You'll need to run `apm link` in that folder for now (this package should be officially launched soon)

You should also installl atom-ide-ui to get the user interface you'll need for most of the features `apm install atom-ide-ui`

**Comment by rcjsuen** [comment]
Thanks, @damieng! It's working now. :)
