### ISSUE TITLE
Code formatting not supported

### ISSUE THREAD

**Issue by EugeneSayko** [atom/ide-typescript#32]
after click ctrl-shift-c Failed to format code: No code formatting providers found!

**Comment by damieng** [comment]
Yes, the ide-typescript package does not include code formatting at this time. We'll need underlying support in the typescript server from Microsoft and the SourceGraph wrapper.

**Comment by UziTech** [comment]
@EugeneSayko You can use [`eslint-format`](https://atom.io/packages/eslint-format) for code formatting with atom-ide-ui and eslint
