### ISSUE TITLE
When editing js with flowtype "'types' can only be used in a .ts file" warning appears

### ISSUE THREAD

**Issue by SpaceHexagon** [atom/ide-typescript#33]
If a file starts with ```//@flow``` the typescript plugin shouldn't run

**Comment by SpaceHexagon** [comment]
I originally had this issue in VSCode and was hoping it would be resolved in Atom Beta 1.2.1

**Comment by Arcanemagus** [comment]
Related to the discussion in #19.

**Comment by damieng** [comment]
You can turn it off entirely for JavaScript from the settings.

I don't think we want to modify a package aimed at TypeScript users to be then specifically looking for and ignoring flow files.

ide-flowtype does exist for flowtype users.

**Comment by SpaceHexagon** [comment]
Fair enough @damieng , the only remaining issue is that the outline fails to populate if I change that setting.

**Comment by damieng** [comment]
Yeah that JS switch is all or nothing right now.  If anyone has any ideas on enabling parts of this or working around some of these limitations without writing our own version of the TypeScript server I'm listening :)
