### ISSUE TITLE
Cannot update ide-typescript 

### ISSUE THREAD

**Issue by petercr** [atom/ide-typescript#36]
I keep getting the same issue when I try to update `ide-typescript` to version 0.6.1.
`EBUSY: resource busy or locked, rmdir 'C:\Users\Cruckshank\.atom\packages\ide-typescript'`
I'm using Atom version 1.12.0-beta0 
![2017-09-15](https://user-images.githubusercontent.com/26460352/30490081-f596b1ec-9a06-11e7-9848-3d24ad7a5d4a.png)

**Comment by damieng** [comment]
If you close the JS file you have open first does the update then work?

**Comment by petercr** [comment]
No I still get the same error 4

**Comment by petercr** [comment]
You can close the problem. After I closed the project and opened a new folder I was able to get ide-typescript to update. Error may have been caused by use of ESLint running in Atom on JavaScript file. Also I was running linter-eslint extension for UI interface.

**Comment by bronson** [comment]
That's good news!  You can also close the problem.  :)

**Comment by petercr** [comment]
Thanks I looked to try to close the issue on GitHub but I couldn't find
where I did that. Good to know for next time.
Thank you

**Comment by developer-lindner** [comment]
Can't update to v0.7.0 ?! Any ideas? @damieng

**Comment by damieng** [comment]
Try quitting Atom and using `apm upgrade ide-typescript` at the command line.

**Comment by developer-lindner** [comment]
![2017-11-09 um 17 24 46](https://user-images.githubusercontent.com/5435866/32616582-f1e08b1c-c572-11e7-9032-1bf1d44c7134.png)

**Comment by damieng** [comment]
So weird that 0.7.0 was on GH but not APM when it's a single command.  

Anyway, have republished 0.7.0 and it's now showing up properly inside Atom.

**Comment by developer-lindner** [comment]
Thank you! Update was available now!

**Comment by benoitcerrina** [comment]
Same problem with the latest update 0.7.5  I had to close atom and remove the package then reinstall it. 
This is the only package I have seen behave like this so I am guessing there is a real issue

**Comment by damieng** [comment]
You can't upgrade while the language server is running - this is a limitation of the atom upgrade system.

You just need to close all .ts and .js files first.
