### ISSUE TITLE
Can't find types in npm @types

### ISSUE THREAD

**Issue by bronson** [atom/ide-typescript#37]
ide-typescript doesn't seem to be finding types from definitelytyped.org.  For example, I install the Chrome types:

`package.json`:

```json
  "devDependencies": {
    "@types/chrome": "^0.0.48",
    "ts-loader": "^2.3.7",
    "typescript": "^2.5.2",
```

And the file compiles without error.  However, ide-typescript doesn't like it:

<img width="841" alt="screen shot 2017-09-15 at 5 52 52 pm" src="https://user-images.githubusercontent.com/1776/30507860-5da75196-9a3f-11e7-91e9-495401487ae8.png">

Any idea how I can make ide-typescript happy?  Thanks!

Atom 1.21.0-beta0, ide-typescript 0.6.1

**Comment by bronson** [comment]
I should point out that not excluding anything, here's my entire tsconfig.

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "es6",
    "target": "es6",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "sourceMap": false,
    "allowJs": true,
    "noEmitOnError": true,
    "outDir": "build"
  }
}
```

I tried variations on

```json
  "include": [
    "node_modules/@types"
  ]
```

and

```json
  "exclude": [
    "node_modules",
    "!node_modules/@types"
  ],
```

but those didn't seem to make any difference.

**Comment by jonyeezs** [comment]
I'm getting the same issue for jasmine

![image](https://user-images.githubusercontent.com/10862726/30574452-52d4faf6-9d3d-11e7-9a13-e7258d591de5.png)

package.json

```json
"devDependencies": {
    "@angular/cli": "1.3.0",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
```

tsconfig.json

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

```

**Comment by felixfbecker** [comment]
Version 2.4.0 of the langserver now supports `typeRoots`: https://github.com/sourcegraph/javascript-typescript-langserver/releases/tag/v2.4.0

**Comment by jonyeezs** [comment]
`ide-typescript` hasn't release an version update to upgrade the new `javascript-typescript-langserver`.

workaround it to uninstall and reinstall the package to get the latest.

Unless someone knows otherwise. Would `apm upgrade` work?

**Comment by damieng** [comment]
ide-typescript 0.6.2 is out that has the new javascript-typescript-langserver 2.4.0 release 

You should just be able to upgrade the ide-typescript package in atom. (no need to uninstall and reinstall ide-typescript)
