### ISSUE TITLE
How could i use "es_module" import to get intellisense in normal "js" file?

### ISSUE THREAD

**Issue by xinleibird** [atom/ide-typescript#39]
Installed DefinitelyTyped `@types` package already, i tried to set `jsconfig.json`

```json
{
  "compilerOptions": {
    "module": "es6",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
  }
}
```

or set `tsconfig.json`

```json
{
  "compilerOptions": {
    "module": "es6",
    "moduleResolution": "node",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
  }
}
```

But only **commonjs** style require function can get intellisense in "js" file like `const foo = require('foo');`.

That **ts** file is works fine with autocomplete and **es_module** system, but **js** file did not.

It's looks like language server initialize issue?
[javascript-typescript-langserver/project-manager.ts#L126](https://github.com/sourcegraph/javascript-typescript-langserver/blob/a0c47d452ef3d7612100a0fda4072bee20f9d333/src/project-manager.ts#L126)

That can be fix but so dirty in `javascript-typescript-langserver/project-manager.ts`......

```javascript
...
                compilerOptions: {
                    module: ts.ModuleKind.ES2015,
                    moduleResolution: 'node',
                    allowSyntheticDefaultImports: true,
                    allowNonTsExtensions: false,
                    allowJs: configType === 'js',
                },
...
```

but it's too dirty.....

Please Please helps and Thanks so much!!!

**Comment by damieng** [comment]
Likely fixed with the new ide-typescript 0.8.0 update.
