### ISSUE TITLE
Hover don't work

### ISSUE THREAD

**Issue by 4ern** [atom/ide-typescript#41]
Hover Feature dont't work?

**Comment by rsese** [comment]
Can you share more details like what are you hovering over?  Can you share the file you're working on?

If you can share a screencast/GIF or screenshots of the behavior, that could be helpful too.

**Comment by 4ern** [comment]
Im work on a angular4 typescript file.
How Hover Highlight should be:

![image](https://user-images.githubusercontent.com/11194583/30688421-6383c788-9ebe-11e7-81ae-d01a714042a4.png)

which does not work with me

![highlight](https://user-images.githubusercontent.com/11194583/30689527-81c41fba-9ec1-11e7-9f7d-150b9f125bbf.gif)

**Comment by rsese** [comment]
> oh I just realized that I have confused hover with highlight.
> sorry

No problem, I'll go ahead and close this issue then.
