### ISSUE TITLE
Feature: Ability to Disable running on JavaScript Files

### ISSUE THREAD

**Issue by keplersj** [atom/ide-typescript#5]
This package is displaying false errors on Flow.js files.

**Comment by jackfranklin** [comment]
Is it possible to have this be a little more intelligent and only not run on JS files with a `// @flow` comment at the top?

In regular JS projects I'd love all the plain JS hinting that this module provides, but in Flow I'd like to turn it off in favour of ide-flow.

**Comment by damieng** [comment]
@jackfranklin there is now an option to disable running on javascript files. Check the settings in Atom for the ide-typescript package.

We don't have a mechanism right now for figuring out how to ignore files based on text content.

**Comment by jackfranklin** [comment]
@damieng yeah I found that setting - thank you! I figure it would be really hard to identity based on file content , just thought I'd ask :)

Thank you for all your great work on this!

**Comment by damieng** [comment]
Yeah as somebody jumping between Flow and TypeScript myself this scenario is definitely on my radar. Just need to find some time and a good approach! :)

**Comment by keplersj** [comment]
@jackfranklin I think you have a good idea. I think it might be better to raise it with the language server instead of `ide-typescript`

**Comment by jackfranklin** [comment]
@keplersj could you point me towards the right GitHub repo? I'm not quite sure which one you mean (sorry - quite new to TypeScript!). I'd be happy to open an issue in the right place.

**Comment by damieng** [comment]
https://github.com/Microsoft/TypeScript
