### ISSUE TITLE
[Feature] Disable linter / error checking

### ISSUE THREAD

**Issue by wyqydsyq** [atom/ide-typescript#55]
I'm currently using `atom-ide` in conjunction with `atom-typescript`, I would prefer to use the linter included in `atom-typescript` as it generally seems to be more responsive however I cannot disable the linter in this plugin resulting in my linter UI (`Diagnostics` pane of `atom-ide`) warnings being shown twice, once from each plugin.

A simple checkbox on the settings page for this plugin to disable this feature would resolve this.

Here you can see the duplicated output, `Typescript` is from `atom-typescript` and `ts` is from this plugin:
![image](https://user-images.githubusercontent.com/621277/31702197-b5d962f8-b418-11e7-90be-e70eab20e54b.png)

This is the behaviour I desire (no linter warnings from `ts` aka `ide-typescript`):
![image](https://user-images.githubusercontent.com/621277/31702230-e0762c08-b418-11e7-8dca-d50f62706f00.png)

**Comment by rsese** [comment]
Thanks for the suggestion - just to clarify, you'd like something more specific than the higher level setting in `atom-ide-ui` where you can disable diagnostics (e.g. so you can turn off diagnostics in `ide-typescript`, but leave it on for another language)?

**Comment by damieng** [comment]
While it's possible to add this option I think we want to avoid the overhead of having every package have a toggle for every feature.

I wouldn't recommend running both these packages - it's going to be running the typescript compiler twice - one for each package - which is going to use 2x the memory and cpu.

**Comment by wyqydsyq** [comment]
I was using both because there were features in `atom-typescript` not available in `ide-typescript`, but I've just realised the only missing feature now is the "Refactor Rename" which I suppose I can live without.

**Comment by wyqydsyq** [comment]
Providing this option would make a suitable workaround for https://github.com/atom/ide-typescript/issues/43 until the incorrect warnings from this package are fixed

**Comment by justintime4tea** [comment]
Perhaps you could have ide-language respect linting rules if found. Maybe ide-typescript can check for, and respect, an .eslintrc or .jshintrc file? When using IDE's like WebStorm I typically end up disabling some of the built-in inspections but in WebStorm it's as easy as alt+enter->edit inspection. That would also be an awesome feature addition to the Atom IDE "parent" package.

**Comment by mshick** [comment]
Also having issues with this plugin applying Typescript linter rules to .js files in projects not using Typescript. The only solution seems to be to disable the package when working on those projects.

**Comment by damieng** [comment]
Will be in the next version https://github.com/atom/ide-typescript/commit/1de64177b1c26abe083b0a556946f4c294e3f750

**Comment by VityaSchel** [comment]
How to specifically disable typescript linter but no eslint?
