### ISSUE TITLE
Code folding and cleanliness

### ISSUE THREAD

**Issue by Announcement** [atom/ide-typescript#57]
Would it be possible to be able to fold the lambdas and such like you can fold stuff in the text editor?
It would also be cool to have an option to synchronize it maybe

**Comment by Arcanemagus** [comment]
I believe this should be filed over on https://github.com/facebook-atom/atom-ide-ui, assuming I'm even understanding what you are asking correctly.

**Comment by damieng** [comment]
I'm not even sure it goes there. Code folding isn't part of LSP or atom-ide-ui...

**Comment by Arcanemagus** [comment]
I _think_ they are talking about the Outline View, and the ability to fold sections of that (with the corresponding section of the code also getting folded).

**Comment by damieng** [comment]
Tree-Sitter is our forthcoming next-generation parsing engine for Atom and will support code folding independently of this project (it will be added to language-typescript over time)
