### ISSUE TITLE
General performance and indication

### ISSUE THREAD

**Issue by damieng** [atom/ide-typescript#6]
Right now ide-typescript is a little slow and it provides no indication of when it is busy.

1. We should improve perf where we can - such as adding streaming supression upstream
2. We should add a status bar or busy indicator when it is doing things

**Comment by deankevorkian** [comment]
Shouldn't the ability at no.2 be supplied / exposed by the atom-languageclient base? I think it's relevant for all LSP providers and could keep a similar behavior between all of them (say if you use busy-signal, you could decide to register a busy-signal provider on the atom language client for all clients to use)

**Comment by damieng** [comment]
I think the concept of when something is busy or not is very provider specific.

For example - diagnostics. There are no starting or completed diagnostics messages in the LSP protocol so we can't auto-wire something up.  A lot of providers however do provide some logging information that indicates when they're starting and when they're done but it's completely not standardized.

**Comment by damieng** [comment]
There have been improvements in the performance of the language server. We will consider whether to use busy state indicators on a case-by-case basis in future releases.
