### ISSUE TITLE
about typescript 2.3 --checkJs

### ISSUE THREAD

**Issue by Dcfm** [atom/ide-typescript#60]
I want to know, [typescript 2.3 --checkJs](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files) can use in ide-typescript? sorry, my English is bad.

**Comment by damieng** [comment]
If there is a .tsconfig setting for that it should be able to read it (not sure if there is for --checkjs).

Unfortunately the underlying language server does not allow us to pass args at this time. You could ask for that to be added as a feature at https://github.com/sourcegraph/javascript-typescript-langserver
