### ISSUE TITLE
Problem interpreting Jquery

### ISSUE THREAD

**Issue by codenome** [atom/ide-typescript#63]
I am having serious problems with interpreting Jquery with this package and I have not been able to solve the problem.

In Visual Studio Code it is working normally.

**Comment by damieng** [comment]
Can you provide more detail?  Does atom hang, does it produce bad results...?

**Comment by franklinyu** [comment]
Global declarations doesn't seem to work in script (file without imports or exports). For example, with `@types/jquery` installed as runtime dependency, in `src/sample.ts` we should be able to directly write

```typescript
var foo: JQuery = $('bar');
```

The above script compiles without warning, but currently `ide-typescript` emits errors.

**Comment by damieng** [comment]
Should now be fixed with the new language server - try ide-typescript 0.8.0
