### ISSUE TITLE
Missing folders included in .gitignore

### ISSUE THREAD

**Issue by Jeymz** [atom/ide-typescript#64]
After installing the latest update any folders included in my .gitignore are no longer in the project file window

**Comment by damieng** [comment]
Files and folders ignored in the .gitignore have always been ignored in the tree-view.  That behavior hasn't changed and is a core part of Atom and it's tree-view, not ide-typescript.

If you don't want that behaviour you can turn off `Hide VCS Ignored Files` in tree-view settings.
