### ISSUE TITLE
Compatibility with ide-flowtype, maybe?

### ISSUE THREAD

**Issue by retrixe** [atom/ide-typescript#66]
I am aware of #8 and the need to disable JavaScript support to provide compatibility in Flow-based projects, but seeing that I have projects in vanilla JavaScript and Flow, If ide-typescript could automatically disable JavaScript support if it detects a .flowconfig in the root directory, it would be helpful. Providing TypeScript's language server support in vanilla JavaScript projects but disabling it in Flow projects would be a very helpful feature. Right now I have disabled it, but I like the availability of Outline View and basic Diagnostics in vanilla JavaScript projects, to jump between objects and classes in my code.

**Comment by Tehnix** [comment]
This would be very nice to have, especially since Atom doesn't really have per-project configs. Either based on the `.flowconfig`, or at the very least if there's a `// @flow` comment at the start of the file.
