### ISSUE TITLE
Change getSuggestions' implementation to only call the base getSuggestions method

### ISSUE THREAD

**Issue by deankevorkian** [atom/ide-typescript#69]
Since ide-typescript is one of the first (if not the first) ide-* packages, some dirty / more general code had to be written inside it, instead of in the base AutoLanguageClient and it's adapters.
After [(WIP) Provide better support for triggering AutoComplete #128](https://github.com/atom/atom-languageclient/pull/128) is merged, we need to remove the implementation from ide-typescript's getSuggestions since the `super class`'es method does it anyway.

**Comment by damieng** [comment]
Unfortunately this is not quite true just yet as the ide-typescript package also splits the returned completionitem up in custom ways. We need to add a hook to atom-languageclient for getSuggestions to be completely removed.

**Comment by deankevorkian** [comment]
Closed in #82
