### ISSUE TITLE
Outline view is very slow

### ISSUE THREAD

**Issue by Haacked** [atom/ide-typescript#70]
Repro steps:

1. Clone https://github.com/desktop/desktop
2. Open the desktop folder in Atom
3. Open the outlive view.
4. Open `app-menu.ts`

Expected: opens in a few seconds.
Actual: Takes 118 seconds.

In talking to @damieng it sounds like there may be some upstream issues with the TypeScript LSP server Atom uses. However, one fix we could do now is to look for `.tsconfig` and start the server when the folder is opened if that file is present. That way, by the time I open a file, the symbols should be in-memory.

The other thing we noticed is there's a _lot_ of file change notifications being sent when there are no changes happening. Not sure that's relevant to this issue, but worth noting.

**Comment by damieng** [comment]
https://github.com/sourcegraph/javascript-typescript-langserver/issues/367

**Comment by damieng** [comment]
Should now be fixed with the new language server - try ide-typescript 0.8.0
