### ISSUE TITLE
Slow diagnostics for imports results in temporary error: File './**/*.ts' is not a module.

### ISSUE THREAD

**Issue by trentrand** [atom/ide-typescript#73]
**Information**
I have been using ide-typescript for a few months and have always had issues with my imports being marked with error: 
`File '/Users/<username>/Developer/<projectName>/src/**/*.ts' is not a module.`

This error underlines **all** imports, including modules.

I have finally noticed what is happening. It appears that there is no debounce on this resolve, and it is taking a considerable amount of time.

See the following gif, noticing how it slowly checks once for each letter inclusion -
![import-issue](https://user-images.githubusercontent.com/6083067/34313798-2c9e8162-e72b-11e7-9e84-3889eed8b366.gif)

**Question**
How can I eliminate this delay? It takes an extremely long time when opening a file, and a few seconds when adding a new import (as shown in gif).

**Comment by damieng** [comment]
Should be fixed with the new ide-typescript 0.8.0 update.
