### ISSUE TITLE
Autocomplete failing in html script tags

### ISSUE THREAD

**Issue by bennypowers** [atom/ide-typescript#76]
Hello 👋 
Lately I started noticing that autocomplete stopped working inside `<script>` tags in HTML on one of my machines.

I checked the dev tools log and found thousands of these errors:

```
Uncaught (in promise) TypeError: Cannot set property 'currentSuggestions' of null
    at TypeScriptLanguageClient.getSuggestions (/Users/bennyp/dotfiles/atom/packages/ide-typescript/lib/main.js:58:40)
```

Sepcifically, the nullable here is the language server, from 
```js
const server = await this._serverManager.getServer(request.editor)
```

Y'all ready for this? if there's a `.js` file open in another tab, autocomplete works a treat. As soon as I close the file, it stops working.

**Comment by bennypowers** [comment]
When `getServer` runs in the case where i don't have a JS file open, `this._activeServers.find(s => finalProjectPath === s.projectPath);` returns `undefined`, which leads me to believe that the js language server does not run when there are no .js files open

**Comment by bennypowers** [comment]
see also https://github.com/atom/ide-typescript/issues/11

**Comment by rwatts3** [comment]
Just curious if there is any progress on intellisense in html files ? or other embedded files where js could exist.

**Comment by damieng** [comment]
Duplicate really of #11 - the LSP spec doesn't talk about embedded languages so we'll need to track the standard.
