### ISSUE TITLE
Are quick fixes implemented? atom-typescript has quick fix for automatically adding imports and its awesome

### ISSUE THREAD

**Issue by chriszrc** [atom/ide-typescript#78]
The atom-typescript has support for quick fixes:

https://github.com/TypeStrong/atom-typescript#quick-fix

Is this implemented or planned for ide-typescript? The thing I want the most at the moment is the ability to resolve missing classes and atom-typescript could automatically find the classes and add them to the imports

**Comment by damieng** [comment]
Should be fixed with the new ide-typescript 0.8.0 update.
