### ISSUE TITLE
Error: "'types' can only be used in a .ts file"

### ISSUE THREAD

**Issue by r24y** [atom/ide-typescript#8]
I'm using the Typescript service to provide code hover and autosuggest for a project that's using JS. I'm using Flow type annotations loosely for documentation purposes, and it really helps improve the quality of the documentation shown on hover; even though Flow and TS are different, I'm really only using the features of Flow that are the same in TS.

However, the Typescript server is giving me a warning when I do this:

![image](https://user-images.githubusercontent.com/8356669/29427038-83a5b4d2-8356-11e7-875a-2753f18a8c99.png)

What would be the best way to disable this warning? I'm willing to complete/submit a PR to either this repo or the languageserver if need be. Even an option to simply disable diagnostics for just this package would help.

**Comment by damieng** [comment]
This is really a limitation of the Typescript server which they have no plans to change https://github.com/Microsoft/TypeScript/issues/7275

Have you tried the [ide-flowtype](https://atom.io/packages/ide-flowtype) extension?  That might be better suited to your needs.

**Comment by r24y** [comment]
Thanks for pointing that out; I'll try it.

**Comment by damieng** [comment]
You can also disable the ide-typescript plugin for javascript if you using both flow and this one (it's in the settings for ide-typescript)

**Comment by KeitIG** [comment]
Maybe it would be more convenient for everyone to create a separated `ide-javascript` package no? I find that "weird" to install `ide-typescript` to have JavaScript support in `atom-ide`.

**Comment by damieng** [comment]
If there was a capable language-server for JavaScript out there we would do just that.

There isn't however :(

**Comment by Cerberus** [comment]
Work fine on 0.7.1

just disable Diagnostics enabled 😄  (don't forget to restart)

![ss](https://user-images.githubusercontent.com/9087409/33757811-62d4912a-dc2e-11e7-9f05-3cc94fea81f5.png)

**Comment by JacopKane** [comment]
@damieng What about using ternjs?

**Comment by damieng** [comment]
TernJS does not support the language server protocol.
