### ISSUE TITLE
Typescript in .js files

### ISSUE THREAD

**Issue by quicoto** [atom/ide-typescript#86]
Hello,

Since Typescript can consume .js files (if enabled in config file) https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#including-js-files-with---allowjs

Is there any change needed in this package? It doesn't seem to work for me.
If I, however rename the file to .ts, it does work.

Ideas?

thank you very much

**Comment by damieng** [comment]
We process JavaScript with this package as well as TypeScript however the .js file must contain just JavaScript - TypeScript is not allowed inside the .js file extension - this is the same as the TypeScript server.

If you are not getting JS syntax checking in your .js files check to make sure the ide-typescript package's settings have the "JavaScript support" setting switched on;

![image](https://user-images.githubusercontent.com/118951/36161098-b09e2540-1097-11e8-94d3-873a4b770b63.png)

**Comment by quicoto** [comment]
Thank you @damieng 

Apparently my problem was in the naming of the config file. I had `tsconfig.json` instead of `jsconfig.json`.

Perhaps this could be written in a documentation somewhere? Or maybe it already is but I couldn't find it?

**Comment by damieng** [comment]
I think that's part of the typescript documentation - given that really we're a bridge between atom and the typescript server I'm not sure how much of the documentation we should duplicate. 

We should probably indicate we use the typescript server and link to their documentation from our own README
