### ISSUE TITLE
ide-typescript doesn't understand some export

### ISSUE THREAD

**Issue by pistou** [atom/ide-typescript#87]
I use `ide-typescript` for an Ionic project, and there is a constant error from `import { Component } from '@angular/core';`

It seems like `ide-typescript`doesn't understand the first line of `angular/core` i.e. 
```export * from './public_api';```
It gives me the error "`File '[...]/node_modules/@angular/core/core.d.ts' is not a module.`"

Same issue with `angularfire2/auth` that has the exact same line.

**Comment by saadq** [comment]
Getting a lot of this with React stuff:

<img width="1440" alt="screen shot 2018-09-30 at 4 36 31 am" src="https://user-images.githubusercontent.com/5678694/46255459-3a180e80-c46b-11e8-9852-7dc0e7a1d82b.png">

Similar problem here, the top error says: `'/Users/me/Projects/inspyre.sh/client/node_modules/@types/react/index.d.ts' is not a module.` which is causing the rest of the React stuff to show errors. I definitely have the React types installed, and running TypeScript itself doesn't result in any errors.

I've tried looking at the source of this package to see if I could help figure out the problem, but it seems very small and I'm guessing the main work is being done elsewhere :/

**Comment by damieng** [comment]
Should be fixed in the new ide-typescript 0.8.0 update.
