### ISSUE TITLE
NPM packages javascript auto completion

### ISSUE THREAD

**Issue by zalishchuk** [atom/ide-typescript#89]
Is installed npm packages API javascript auto completion supported now as it works in Visual Studio Code?

**Filename:** index.js
**Atom version**: 1.25.0-beta0 x64
**Grammar:** language-babel

Visual Studio Code example:
![image](https://user-images.githubusercontent.com/2690794/36347415-549d9214-145f-11e8-9f1b-f49b436b03d5.png)

Atom Beta example:
![image](https://user-images.githubusercontent.com/2690794/36347418-622e527e-145f-11e8-83dc-3f02b3904a8f.png)

**Comment by ProtonScott** [comment]
I would like to second this. Does not appear to be any different on the latest release either. This is a *must have* feature I feel like should be top priority for this extension.

**Comment by zalishchuk** [comment]
Ok, the solution now is installing typings from `@types`, but Visual Studio Code uses [Automatic Type Acquisition](https://code.visualstudio.com/docs/languages/javascript#_automatic-type-acquisition) and handles typings for packages installed in `package.json` itself, can we have the same feature added in `ide-typescript`?

**Comment by Viceriel** [comment]
I'm big fan of atom, but this feature is really missing. I think like @ProtonScott hinted, this feature is big advantage of VS Code above Atom.

**Comment by damieng** [comment]
Should be fixed with the new ide-typescript 0.8.0 update.
