### ISSUE TITLE
TypeScript (SourceGraph) language server has exited

### ISSUE THREAD

**Issue by lincolnfrias** [atom/ide-typescript#90]
When I open atom with a js file or try to open the Outline View afterwards  I get:

    The TypeScript (SourceGraph) language server has exited and exceeded the restart limit for project '/home/lincoln/'

As a background, ide=python is working fine. Any clues?

My setup: 
Atom 1.24.0, on Ubuntu 16.04. 

Installed packages:
atom-ide-ui@0.8.1
greek-snippets@0.1.0
ide-python@0.8.0
ide-typescript@0.7.3
markdown-folding@0.1.0
markdown-writer@2.7.3
wordcount@2.10.4

**Comment by rsese** [comment]
Thanks for the report - so this happens if you open any JavaScript file from any project or just JavaScript from a particular file/project?  And can you share an example project where you get this error so we can give it a try?

Lastly, do you happen to have both a Python project and JavaScript project open at the same time when you get this error?

**Comment by lincolnfrias** [comment]
@rsese thanks a lot, you solved it. I was trying to open js files along with markdown ones. Opening a new atom instance solely for js files solves the problem. Thank you very much!

**Comment by DamnedScholar** [comment]
I wouldn't consider this solved. If `ide-typescript` is truly crashing when a JavaScript file and a Markdown file are both open at the same time, that's a serious issue that could affect many people. @lincolnfrias can you confirm that the crash is replicable by having two files with different grammars? Is it only JS/Markdown, or do other combinations also cause a crash?

**Comment by lincolnfrias** [comment]
@DamnedScholar The problem is not happening anymore. I tried different folders, atom instances with markdown files already opened or opened afterwards and everything is working fine now. I'll let you know if it happens again. Thanks for your attention.

**Comment by am** [comment]
I do share the same problem. Is there any logs I can share to help debug the problem?

**Comment by rsese** [comment]
@am if you have a reproducible problem, please open a new issue and share as much information as you can (e.g. what operating system, what version of Atom, steps to reproduce, etc.) - if you can share a specific project that we can test with, that would be helpful too.
