### ISSUE TITLE
Respect the min word length setting on autocomplete

### ISSUE THREAD

**Issue by jackfranklin** [atom/ide-typescript#91]
Hello :)

One thing that seems to have changed in a recent update is that the suggestions placed into autocomplete by TypeScript now seem to not respect the min-word-length setting of autocomplete-plus.

I have this set to the default which is 3, but from the moment I type anything my autocomplete gets filled with huge lists of TypeScript suggestions. I have this setting at 3 to avoid getting loads of irrelevant suggestions before I've typed enough to give the IDE a hint of what I'm after, and it would be great to have TypeScript respect this.

I'm unsure if this belongs in this repo, or in the language server, or in atom-ide, so please excuse me if I've put this in the wrong place. Thank you all for you work on this, it's giving me a really nice working environment :)

**Comment by damieng** [comment]
ide-typescript has never honored this - the setting in autocomplete-plus may or may not be honored by autocomplete providers (as per the docs).

Right now we do have some terrible autocomplete suggestions and I have a couple of things in-flight that will make them much better without having to fall back to the 3 character situation.

**Comment by damieng** [comment]
We decided to actually honor this when we're not on a trigger character (i.e. typing `this` will only trigger once it gets to the `i` but typing `this.` will trigger on the dot even thought it's not a 3 character word at that point.

This happened upstream in to atom-languageclient 0.9.0 updated here in 6fca8310909e9ea71c9bcae9a563b6f587a1ed94 !

Now published as ide-typescript 0.7.4
