### ISSUE TITLE
Autocomplete shows irrelevant suggestions

### ISSUE THREAD

**Issue by andrictham** [atom/ide-typescript#93]
After updating the package to the latest version, 0.7.3, everytime I type a space or colon character in a .js file, I start to see irrelevant suggestions for things like `SVGFEFuncBElement` or `SVGFEMergeNodeElement` (see image below). This makes the editor unusable since everytime I do a space, colon, or semi-colon character followed by a return, I will accidentally choose an autocompleted snippet I don’t want.

<img width="674" alt="screen shot 2018-02-21 at 1 59 44 pm" src="https://user-images.githubusercontent.com/3891147/36465550-9bebf2c4-1710-11e8-8167-c9a291c54eb8.png">

My installed snippets no longer show up at the top. Instead, the show up at the bottom of the autocompletion list or not at all. Disabling `ide-typescript` returns behavior to the normal, expected behavior. 

If I downgrade `ide-typescript` to 0.7.2 by running `apm uninstall ide-typescript` and then `apm install ide-typescript@0.7.2`, then my snippets and autocompletions show up as expected again (see image below). I am not sure what the cause of this is.

<img width="1132" alt="screen shot 2018-02-21 at 2 07 19 pm" src="https://user-images.githubusercontent.com/3891147/36465552-9c1ad896-1710-11e8-8b03-b9f13644c9c2.png">

Related issues: #91

**Comment by pbrandone** [comment]
+1

**Comment by yuzhakovvv** [comment]
When I try to use `log` snippet, autocomplete shows totally irrelevant suggestions above it. Is there an option to show snippets above? `ide-typescript@0.7.2` works fine.

![image](https://user-images.githubusercontent.com/10023109/36497869-8f7bb7e6-170a-11e8-9877-a1874d012427.png)

**Comment by Powell-v2** [comment]
+1, very annoying ... 😞

**Comment by garza** [comment]
+1

**Comment by adamjsimon** [comment]
+1

**Comment by daviwil** [comment]
We are looking into a fix for this issue, thanks for all the feedback so far!

**Comment by JSn1nj4** [comment]
Thanks!

**Comment by matt3224** [comment]
Yes! This issue is plaguing me too. Its the worst! So much so i have just switched off autocomplete-plus

**Comment by damieng** [comment]
Much improved autocomplete via an update to atom-languageclient in 6fca8310909e9ea71c9bcae9a563b6f587a1ed94 !

**Comment by Tol1** [comment]
Seems like this never fixed, or the error is back. This is what I get every time defining an array or object, after comma: 
![image](https://user-images.githubusercontent.com/1314529/38889467-7bb8de8e-4287-11e8-8ec5-73ccc5f42e5b.png)
Had to disable "select with enter", because defining object was impossible with those suggestions. 
Using version 0.7.6 of ide-typescript, and disabling package hides those irrelevancies.

**Comment by mattgrosso** [comment]
I am also still experiencing this issue. It makes this package all but unusable for me.

(Atom 1.26.0, ide-typescript 0.7.6)

**Comment by matt3224** [comment]
I'm still experiencing frustrations with this too. If i'm in css and typing inside a declaration i almost always want a property like `top` I do not want `// TODO: ` I hope this can be reopened and improved.

I appreciate all the work that has gone in to it so far though!

**Comment by damieng** [comment]
@matt3224 That will be an issue elsewhere, this does not add autocomplete suggestions to css files, only .js, .jsx, .ts and .tsx files.
