### ISSUE TITLE
Support ".mjs" file extension (required by Node.js to load ES modules)

### ISSUE THREAD

**Issue by EvilOatmeal** [atom/ide-typescript#94]
Node.js requires that ES modules to use the ".mjs" file extension so that it knows to load them using ES modules instead of CommonJS modules. This is mentioned in the [Node.js documentation for ES modules](https://nodejs.org/api/esm.html#esm_enabling).

Currently ".mjs" files are ignored by this extension or the language server, I'm not sure which.

**Comment by damieng** [comment]
It's a limitation of the typescript language server - the issue upstream is https://github.com/Microsoft/TypeScript/issues/18442

**Comment by EvilOatmeal** [comment]
Thank you!

**Comment by damieng** [comment]
If and when this happens upstream feel free to comment or re-open this issue so we can do the necessary work our side to make sure it works :)  Thanks!
