### ISSUE TITLE
Autocomplete suggestions don't appear to take into account the context in which they're being presented

### ISSUE THREAD

**Issue by ryancole** [atom/ide-typescript#98]
I don't know how to phrase what I want to say, so here goes my best attempt ...

Autocomplete suggestions don't appear to take into account the context in which they're being presented.

By that I mean, with the following code ...

```
import * as MattersApi from "../../api/matter";
import * as MattersAction from "../actions/matters";

MattersApi.<suggestion appears here>
MattersAction.<suggestion appears here>
```

The suggestions will simply include all detected items from both imports.

I had expected it to show suggestions based on the import in the context of the popup.

**Comment by damieng** [comment]
Likely fixed with the new ide-typescript 0.8.0 update.
