### ISSUE TITLE
"Go to declaration" does not work

### ISSUE THREAD

**Issue by marcos-diaz** [atom/ide-typescript#99]
Built-in functionality "Go to declaration" (at the right-click menu) does nothing, neither a custom shortcut with equivalent result is provided by `ide-typescript`.

I'm assuming this should work since the project README claims "Features -> Go to definition"

atom: 1.25
OS: MacOS 10.13.3
ide-typescript: 0.7.6
atom-ide-ui: 0.9.4

P.S.: Find references, compiler errors, and other functionalities works fine.

**Comment by damieng** [comment]
You'll need to control-click on the item to 'go to definition'

The item in the menu confusingly called 'go to declaration' is in fact part of symbols-view which is unaware of ide packages and behavior.
